"""Inicial Render

Revision ID: 890242735cd9
Revises: 
Create Date: 2025-11-07 19:22:58.185886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '890242735cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('appointment_type', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('treatment_type', sa.String(length=120), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Nota: No eliminamos tablas existentes de esquemas previos
    # para evitar romper claves foráneas. Esta migración sólo crea
    # las nuevas tablas requeridas por la aplicación actual.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id_historial', sa.INTEGER(), server_default=sa.text("nextval('historial_id_historial_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_mascota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascota.id_mascota'], name='historial_id_mascota_fkey'),
    sa.PrimaryKeyConstraint('id_historial', name='historial_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.INTEGER(), server_default=sa.text("nextval('rol_id_rol_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name='rol_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_usuario_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('contrasena', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], name='usuario_id_rol_fkey'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey'),
    sa.UniqueConstraint('cedula', name='usuario_cedula_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('correo', name='usuario_correo_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cita',
    sa.Column('id_cita', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_mascota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('veterinario', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado::text = ANY (ARRAY['Pendiente'::character varying, 'Completada'::character varying, 'Cancelada'::character varying]::text[])", name=op.f('cita_estado_check')),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['Vacunación'::character varying, 'Consulta'::character varying, 'Cirugía'::character varying, 'Control'::character varying, 'Desparasitación'::character varying, 'Otro'::character varying]::text[])", name=op.f('cita_tipo_check')),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascota.id_mascota'], name=op.f('cita_id_mascota_fkey')),
    sa.PrimaryKeyConstraint('id_cita', name=op.f('cita_pkey'))
    )
    op.create_table('mascota',
    sa.Column('id_mascota', sa.INTEGER(), server_default=sa.text("nextval('mascota_id_mascota_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('especie', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('raza', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('alergias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name='mascota_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_mascota', name='mascota_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tratamiento',
    sa.Column('id_tratamiento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_historial', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vacuna', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dosis', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_historial'], ['historial.id_historial'], name=op.f('tratamiento_id_historial_fkey')),
    sa.PrimaryKeyConstraint('id_tratamiento', name=op.f('tratamiento_pkey'))
    )
    op.drop_table('treatments')
    op.drop_table('appointments')
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
